# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a350c3ccda1170dc5bdafce9bd8065d5"
name = "tutorial-rails-app"
handle = "tutorial-rails-app"
application_url = "https://adjacent-rd-listings-fee.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-24eb93de.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://adjacent-rd-listings-fee.trycloudflare.com/auth/callback",
  "https://adjacent-rd-listings-fee.trycloudflare.com/auth/shopify/callback",
  "https://adjacent-rd-listings-fee.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
