# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "004188b8d53cd83d6c38ab1a7ca09fc4"
name = "tutorial-rails-app"
handle = "tutorial-rails-app-2"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
